---
title: "CPM-PERT model"
author: "Andrej Sokolič, Manca Cör"
date: "04 januar 2017"
output: pdf_document
---

# Metodi CPM in PERT

Podan imamo projekt, ki je sestavljen iz množice *n* opravil. Za vsako opravilo *o* imamo podano trajanje, lahko pa tudi množico drugih opravil, ki jih moramo opraviti pred začetkom opravila *o*. 
Projekt lahko upravljamo preko dveh sorodnih metod.

- Prva se imenuje CPM (*critical path method*), pri kateri imamo trajanje posameznega opravila podano deterministično. CPM metoda je uporabna predvsem pri projektih, kjer je mogoče precej natančno določiti trajanje opravil. 

- Druga metoda se imenuje PERT (*project evaluation and review technique*), kjer je trajanje opravila podano kot diskretna slučajna spremenljivka s tremi podanimi ocenami za trajanje projekta: optimistično, pesimistično in najbolj verjetno. V tem primeru računamo pričakovan čas trajanja celotnega projekta ali verjetnost, da bo projekt zaključen v določenem roku.

Pri obeh metodah lahko projekt predstavimo kot graf:

- vozlišča so natanko podana opravila, dodamo pa še dve dodatni vozlišči in sicer *s* (*0*) - start in *z* (*n+1*) - zaključek.

- povezave: usmerjeno povezavo iz opravila *i* v *j* dodamo, če je opravilo *i* pogoj za začetek opravljanja opravila *j*. Če vozlišče *i* nima nobenih pogojev, dodamo povezavo iz *s* v *i* in če *j* ni pogoj za nobeno drugo opravilo, dodamo povezavo iz *j* do *z*.  

- utež na povezavi od *i* do *j* je natanko trajanje opravila *i*. Opravili *s* in *z* imata trajanje 0. 

Če je graf brez ciklov, potem je projekt smiseln (če bi bilo opravilo *i* pogoj za poravilo *j* in opravilo *j* pogoj za opravilo *i*, bi bil projekt neizvedljiv. Isto velja tudi za daljše cikle.). V tem primeru imamo za graf topološko urejanje, s katerim lahko določimo vrstni red opravljanja opravil. To pomeni, da pred opravilom *j* opravimo vsa opravila iz njegove množice opravil, ki so pogoj za začetek njegovega opravljanja.

Pri obeh metodah iščemo kritično pot, to je pot v grafu, kjer so vsa opravila kritična. Posamezno opravilo *o* je kritično, če pri začetku opravljanja opravila *o* nimamo fleksibilnosti (to pomeni, da začetka opravljanja opravila *o* ne moremo prestaviti na poznejši čas, brez da bi s tem podaljšali čas izvajanja projekta). 

V najinem projektu se bova osredotočila na metodo PERT (oziroma na njeno različico), ker bodo trajanja različnih opravil podana kot slučajne spremenljivke. Te slučajne spremenljivke ne bodo imele le treh možnih vrednosti trajanja opravila, ampak bodo porazdeljene po različnih porazdelitvenih zakonih. Najin cilj je določiti pričakovano vrednost trajanja projekta pri različnih porazdelitvah trajanja posameznega opravila. 

# Metoda Monte Carlo

Za računanje pričakovane vrednosti trajanja bova uporabila metodo Monte Carlo. Monte Carlo je metoda, ki pri reševanju problemov uporablja verjetnost oz. naključnost. Uporablja se predvsem za numerično reševanje težkih problemov, ki jih ni mogoče oz. jih je zelo težko rešiti s pomočjo drugih znanih metod. Ta metoda se je zelo razvila šele v zadnjih 30 letih, ko se je zmogljivost računalnikov zelo povečala.

Metoda Monte Carlo temelji na tem, da določen "poskus" ponovimo zelo velikokrat, pri tem pa uporabljamo psevdo slučajnost. Na koncu izmed vseh dobljenih rezultatov lahko dobimo porazdelitev, matematično upanje... Natančnost postopka lahko določimo iz standardnega odklona. Teoretična osnova za to metodo je centralni limitni izrek.

Metoda Monte Carlo je zalo uporabna, predvsem ker načeloma ni pomembno kako komplicirani so podatki (v najinem primeru naprimer za samo metodo ni pomembno kako je porazdeljena slučajna spremenljivka trajanja posameznega opravila). Ta metoda nam omogoča precej dobro simulacijo realnega scenarija, sploh če imamo dovolj zmogljiv računalnik za res velikokratno ponovitev poskusa. 

Glavni problem te metode je povezan z naključnostjo. Računalnik namreč ne zna generirati zares naključnih števil, le psevdo naključna. To pomeni, da so števila le navidezno slučajna, v resnici pa so vseeno odvisna od nekaterih zunanjih dejavnikov, odvisno od algoritma. V resničnem življenju je naključnost res naključna, kar lahko pripelje do odstopanj. 


Problem te metode nasopi tudi, če želimo izračunati zelo majhne oziroma zelo natančne vrednosti. Hitrost oz. natančnost metode je omejena s centralnim limitnim izrekom, zato za vsako novo decimalko potrebujemo veliko (okrog 100 krat) več časa kot za prejšnjo. 

# Plan dela

Pri projektu bova najprej naredila program, ki bo za dano tabelo projekta (trije vektorji: *opravilo*, *seznam predhodnih opravil* in *trajanje opravila*) vrnil vrstni red opravljanja in optimalni čas trajanja celotnega projekta. Nato bova z metodo Monte Carlo za izbran določen projekt simulirala čas trajanja celotnega projekta, kjer bodo trajanja posameznega opravila slučajne spremenljivke z določeno porazdelitvijo. S to metodo bova tudi dobila približek pričakovanega trajanja projekta, rezultate pa bova tudi analizirala glede na standardni odklon.



##############################################################

Preizkusimo sedaj kako se čas trajanja projekta spremeni, če determinističnim časom trajanja opravil priredimo slučajne
spremenljivke. Za porazdelitev časov trajanja izberemo porazdelitve: enakomerno zvezno, normalno in
binomsko.
Začnemo tako, da definiramo funkcijo, ki determinističnemu vektorju priredi slučajni vektor časov trajanja opravil.
Kot argument bo funkcija sprejela determinističen vektor in različne parametre, odvisne od izbrane slučajne spremenljivke.
Prvo definiramo prazen vektor enake dolžine kot vektor časov trajanja opravil. Nato vzamemo vsak čas iz slednjega in mu priredimo slučajno spremenljivko tako, da bo njeno matematično upanje enako prvotnemu času trajanja opravila. To slučajno spremenljivko nato zapiše v prej definiran prazen vektor in tako na koncu dobimo željeni slučajni vektor.

Sedaj, ko so funkcije definirane, lahko pričnemo s simulacijo z raznimi slučajnimi spremenljivkami in njihovimi 
variacijami. Opazujemo kako spreminjanje parametrov in izbira slučajne spremenljivke vpliva na čas trajanja projekta ter poskusimo poiskati povezavo med standardnim odklonom slučajnih spremenljivk in časom trajanja projekta.
Za vsako različno simulacijo narišemo tudi histogram z označenim matematičnim upanjem in standardnim odklonom in graf, ki prikazuje kako standardni odklon slučajnih časov trajanja vpliva na povprečno trajanje projektov. Za narisat slednjega si pomagamo z matriko, v katero po stolpcih zapišemo različne simulacije časov trajanja projekta, po vrsticah pa različne standardne odklone.

Za vse simulacije uporabimo enake vektorje opravil, časov trajanja opravil in predhodnikov:
Opr<-(1:18)
Pred<-list(c(0),c(1),c(2),c(3),c(4,17),c(5),c(6),c(6),c(2,10),c(1),c(10),c(11),c(12,17),c(13),c(11),c(15,3),c(9,15,16),c(5,13))
Cas<-c(5,3,4,9,12,3,1,7,5,1,3,6,5,3,4,9,12,3)


Začnimo s premaknjeno normalno porazdelitvijo, to je normalna porazdelitev z navzgor ali navzdol omejeno zalogo vrednosti.

Funkcija kot argument sprejme vektor časov trajanja, koeficient, ki omejuje najnižjo možno dosegljivo vrednost, ki jo lahko slučajna spremenljivka zasede (kot delež danega časa trajanja opravila) in standardni odklon porazdelitve.

Za parametre izberemo standardno deviacijo 1, in koeficient 0.8 - za opravilo porabimo vsaj 80% predvidenega časa.

Sedaj 10000-krat izračunamo čas trajanja projekta in dobimo vektor dolžine 10000.
Matematično upanje: 58.64452
Standardni odklon: 2.447101
Minimum: 51.16575
Maximum: 69.95254

Sedaj pa fiksirajmo koeficient na 0.8 in spreminjajmo standardni odklon posameznih opravil od 0 do 3, s korakom 0.05.

Iz grafa je razvidno da se z večanjem standardnega odklona veča tudi čas trajanja projekta, povezava med njima izgleda
linearna.

Z večanjem(manjšanjem) vrednosti koeficienta se pričakovano veča (manjša) tudi čas trajanja projekta. Standardni odklon trajanj projektov pa se (tudi pričakovano- zaradi manjše(večje) zaloge vrednosti slučajne spremenljivke) manjša (veča).



Poglejmo sedaj trajanje projekta, ko so časi trajanj opravil porazdeljeni enakomerno zvezno.

Funkcija kot argument sprejme vektor časov trajanja opravil, in koeficient, s katerim določimo simetričen interval s središčem v prvotnem času.

Koeficient izberemo 0.5, torej vsakemu času bo dodeljena slučajna spremenljivka, ki je enakomerno zvezno porazdeljena na intervalu [0.5 * čas, 1.5 čas].

Zanimivo je, da kljub temu, da so časi porazdeljeni simetrično, torej bi v povprečju pričakovali enak čas kot za deterministične čase, dobimo trajanja ki so v povprečju malo daljša od 56 dni.

Spreminjajmo sedaj koeficient, od 1 do 0, pri čemer bo pri vrednosti 1 dobimo čas enak prvotnemu, pri vrednosti 0 pa največji možen interval, torej [0, 2 * čas]. Z manjšanjem koeficienta se torej standardni odklon povečuje.
Poglejmo kako to vpliva na čas trajanja projekta.

Z večanjem standardnega odklona se veča razpršenost trajanja opravil in v povprečju tudi čas trajanja projektov.


Nadaljujmo s podobnim primerom, le da sedaj naslednjega opravila ne moremo začeti na isti dan kot smo končali predhodnika. Imamo torej slučajni vektor z diskretnimi in zvezbuni slučajnimi spremenljivkami.
Funkcija sprejme iste argumente kot prej in kot prej izberemo koeficient 0.5. 

Pričakovano dobimo čas trajanja, ki je daljši od tistega pri enakomerno zvezni porazdelitvi.





Poiskusimo sedaj modelirati čase še z binomsko porazdelitvijo.
Funkcija kot argument sprejme vektor časov trajanja opravil in število poskusov. Število poskusov izberemo kot argument za lažje opazovanje povezave med standardnim odklonom in trajanjem projekta, saj je standardni odklon kot funkcija števila poskusov naraščajoča funkcija.
Verjetnost uspeha izračunamo kot kvocient prvotnega časa in števila poskusov.




Dodatno lahko dodamo še pogoj, da posameznega opravila ni mogoče končati prej kot v npr. 80% določenega časa.


